# 配置文件

DAILY_TIME: "08:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-05-20" # 纪念日
CITY: "安康"

BIRTHDAY:
  - "01-16"

APP_ID: "wx27b385446a07c263"
APP_SECRET: "8c256ec381e5e09d00c5db3a8d2a53de"

USER_ID: 
  - "ozwEU5_UoOc8Yvqma0qhpjCuIz-s"
  
TEMPLATE_ID: "	ouktZBAupAmD1NTA58um_WxoKaiVx3p6DPI-R3-JcJw"
